# Generated by Django 5.2.17 on 2026-09-21 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('web', 'Web Application'), ('mobile', 'Mobile Application'), ('ai-ml', 'AI / Machine Learning'), ('robotics', 'Robotics / IoT'), ('desktop', 'Desktop App'), ('cli-script', 'CLI / Automation Script'), ('game', 'Game Development'), ('other', 'Other')], default='web', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
